# Generated by Django 3.1.7 on 2021-03-15 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('category', models.CharField(default='Employee', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60)),
                ('mail1', models.CharField(max_length=60, null=True)),
                ('mail2', models.CharField(max_length=60, null=True)),
                ('mail3', models.CharField(max_length=60, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailsapp1.employee')),
            ],
        ),
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_mail_id', to='mailsapp1.mail')),
                ('recipient_mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_mailbox_id', to='mailsapp1.mailbox')),
                ('response_mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_mail_id', to='mailsapp1.mail')),
                ('sender_mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_mailbox_id', to='mailsapp1.mailbox')),
            ],
        ),
    ]
