# Generated by Django 3.1.7 on 2021-03-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Employee', 'Employee'), ('Director', 'Director')], default='Employee', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_adress', models.CharField(max_length=60)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailsapp1.employee')),
            ],
        ),
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_resp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailsapp1.mail')),
            ],
        ),
    ]
