# Generated by Django 3.1.7 on 2021-03-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mail_address',
            name='address',
            field=models.EmailField(max_length=80),
        ),
    ]
