# Generated by Django 3.1.7 on 2021-03-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailsapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='id_resp',
            new_name='resp',
        ),
        migrations.RenameField(
            model_name='mailbox',
            old_name='id_employee',
            new_name='employee',
        ),
    ]
