# Generated by Django 3.1.7 on 2021-03-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailsapp1', '0002_auto_20210318_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='sender_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_mail_id', to='mailsapp1.mail_address'),
        ),
    ]
