# Generated by Django 3.1.7 on 2021-03-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailsapp1', '0003_auto_20210326_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='recipient_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_mail_id', to='mailsapp1.mail_address'),
        ),
    ]
