# Generated by Django 2.2.10 on 2021-05-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('inEnron', models.BooleanField()),
                ('category', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('enron_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('isReply', models.BooleanField(null=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='app.mailAddress')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app.mailAddress')),
            ],
        ),
    ]
