# Generated by Django 2.2.10 on 2021-04-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('inEnron', models.BooleanField()),
                ('category', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=200)),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Mailbox')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enron_id', models.CharField(max_length=120)),
                ('date', models.DateTimeField(null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('isReply', models.BooleanField(null=True)),
                ('mailbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Mailbox')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_mail_id', to='app.mailAddress')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_mail_id', to='app.mailAddress')),
            ],
        ),
    ]
