# Generated by Django 2.2.10 on 2021-05-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
