# Generated by Django 2.2.10 on 2021-04-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210415_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='mailbox',
            new_name='mailbox_id',
        ),
    ]
