# Generated by Django 2.2.10 on 2021-04-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210415_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='mailbox_id',
            new_name='mailbox',
        ),
    ]
