# Generated by Django 2.2.10 on 2021-04-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210415_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inEnron', models.BooleanField()),
                ('last_name', models.CharField(max_length=40, null=True)),
                ('first_name', models.CharField(max_length=40, null=True)),
                ('category', models.CharField(default='Employee', max_length=40, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mail',
            name='recipient_mail',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='sender_mail',
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='last_name',
        ),
        migrations.AddField(
            model_name='mail',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_id', to='app.user'),
        ),
        migrations.AddField(
            model_name='mail',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='app.user'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
