# Generated by Django 2.2.10 on 2021-04-16 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210416_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
