# Generated by Django 2.2.10 on 2021-04-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210416_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='next_mail',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='previous_mail',
        ),
        migrations.AddField(
            model_name='mail',
            name='response',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='mail_address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
