# Generated by Django 2.2.10 on 2021-04-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210416_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='user',
        ),
        migrations.AddField(
            model_name='mail',
            name='recipient_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_mail_id', to='app.user'),
        ),
        migrations.AddField(
            model_name='mail',
            name='sender_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_mail_id', to='app.user'),
        ),
    ]
