# Generated by Django 2.2.10 on 2021-04-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210416_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='recipient_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_mail_id', to='app.mail_address'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_mail_id', to='app.mail_address'),
        ),
    ]
