# Generated by Django 2.2.10 on 2021-04-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210416_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail_address',
            old_name='user',
            new_name='usr',
        ),
    ]
