# Generated by Django 2.2.10 on 2021-04-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210421_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='usr',
        ),
    ]
