# Generated by Django 2.2.10 on 2021-04-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210421_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usr',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='mail_address',
            old_name='usr',
            new_name='user',
        ),
    ]
