# Generated by Django 2.2.10 on 2021-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210422_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail_address',
            name='address',
            field=models.EmailField(max_length=100),
        ),
    ]
