# Generated by Django 2.2.10 on 2021-04-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210422_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='mail_date',
            new_name='date',
        ),
    ]
